name: Azure MCP - releases

permissions:
  contents: write
  issues: write

on:
  schedule:
    - cron: '0 1 * * *' # Runs daily
  workflow_dispatch:

jobs:
  check-mcp-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Get MCP releases in last 24 hours
        id: recent_releases
        run: |
          chmod +x ./scripts/azure-mcp-release.sh
          ./scripts/azure-mcp-release.sh
          echo "found=$(cat ../.github/mcp-release.md | wc -l)" >> $GITHUB_OUTPUT
          echo "GITHUB_OUTPUT contents:"
          cat $GITHUB_OUTPUT

      - name: Read last known MCP release tag
        id: last_release
        run: |
          if [ -f .github/mcp-release.txt ]; then
            echo "last=$(cat .github/mcp-release.txt)" >> $GITHUB_OUTPUT
          else
            echo "last=" >> $GITHUB_OUTPUT
          fi
          echo "GITHUB_OUTPUT contents:"
          cat $GITHUB_OUTPUT

      - name: Show outputs in log
        run: |
          echo "Recent releases found: ${{ steps.recent_releases.outputs.found }}"
          echo "Last known MCP release tag: ${{ steps.last_release.outputs.last }}"

      - name: Create issue if new MCP release
        if: steps.latest_release.outputs.tag != steps.last_release.outputs.last
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: "New MCP Release: ${{ steps.latest_release.outputs.tag }}"
          content-filepath: mcp-release.txt
          labels: mcp-release
          token: ${{ secrets.GH_PAT }}

      - name: Update tracked MCP release tag
        if: steps.latest_release.outputs.tag != steps.last_release.outputs.last
        run: |
          echo "${{ steps.latest_release.outputs.tag }}" > .github/mcp-release.txt
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .github/mcp-release.txt
          git commit -m "Update tracked MCP release tag"
          git push